name: Sync Home Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3

    - name: Clone the 'home' repo
      env:
        TOKEN: ${{ secrets.PAT }}
      run: |
        # Clone the 'home' repo into a temporary directory
        git clone https://jasuovu:$TOKEN@github.com/jasuovu/home.git /tmp/home

        # Remove the existing files in the home directory
        rm -rf /tmp/home/*

        # Copy the current repo's content into the 'home' repo folder
        cp -r ./* /tmp/home/

        # Go into the 'home' directory
        cd /tmp/home

        # Configure Git
        git config user.name "jasuovu"
        git config user.email "jasuovu@gmail.com"

        # Commit and push the changes
        git add .
        git commit -m "Sync from jasuovu.github.io"
        git push
