name: Sync Home Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3

    - name: Clone the 'home' repo
      env:
        TOKEN: ${{ secrets.PAT }}
      run: |
        # Clone the 'home' repo
        git clone https://jasuovu:$TOKEN@github.com/jasuovu/home.git

        # Remove the existing files in the home directory
        rm -rf home/*

        # Copy all files from the current repo to 'home/' excluding the 'home' directory itself
        rsync -av --exclude 'home' ./ home/

        # Go into the 'home' directory
        cd home

        # Configure Git
        git config user.name "jasuovu"
        git config user.email "jasuovu@gmail.com"

        # Commit and push the changes
        git add .
        git commit -m "Sync from jasuovu.github.io"
        git push
